shortlink/accounts/urls.py
from django.urls import path

from .views import login_view, register_view, get_profile, logout_view

app_name = 'accounts'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('register/', register_view, name='register'),
    path('profile/', get_profile, name='profile'),
    path('logout/', logout_view, name='logout'),
]

shortlink/main/urls.py
from django.urls import path

from .views import start_page, short_link, revers_transformation, list_links

app_name = 'main'
urlpatterns = [
    path('', start_page, name='start_page'),
    path('short_link/', short_link, name='short_link'),
    path('<slug:slug>', revers_transformation, name='revers_transformation'),
    path('list_links/', list_links, name='list_links'),

]

shortlink/shortlink/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
]

shortlink/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    """ класс пользователя сайта """

    class Meta(AbstractUser.Meta):
        pass

shortlink/main/models.py
from django.conf import settings
from django.db import models


class ShortLink(models.Model):
    """ модель для сокращенния ссылки """

    full_link = models.URLField(unique=True, verbose_name='Полная ссылка в формате http://...')
    slug = models.CharField(max_length=28, unique=True, blank=True, verbose_name='Сокращенная ссылка')
    date_created = models.DateTimeField(auto_now_add=True, verbose_name='дата и время сокращения ссылки')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Пользователь')

    class Meta:
        ordering = ["-date_created"]

    def __str__(self):
        return self.full_link

shortlink/accounts/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError

from .models import CustomUser


class LoginForm(forms.Form):
    """ класс авторизации пользователя """

    username = forms.CharField(label='Логин', max_length=100)
    password = forms.CharField(label='Пароль', max_length=100, widget=forms.PasswordInput())


class CustomUserRegisterForm(forms.ModelForm):
    """ класс регистрации пользователя """

    # email = forms.EmailField(required=True, label="Адрес электронной почты")
    password1 = forms.CharField(widget=forms.PasswordInput, label="Пароль",
                                help_text=password_validation.password_validators_help_text_html())
    password2 = forms.CharField(widget=forms.PasswordInput, label="Повторите пароль",
                                help_text="введите пароль еще раз")

    def clean_password1(self):
        password1 = self.cleaned_data['password1']
        if password1:
            password_validation.validate_password(password1)
        return password1

    def clean(self):
        super().clean()
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 and password2 and password1 != password2:
            errors = {'password2': ValidationError('Введенные пароли не совпадают', code='password_mismatch')}
            raise ValidationError(errors)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user

    class Meta:
        model = CustomUser
        fields = ['username', 'password1', 'password2']

shortlink/main/forms.py
from django import forms

from .models import ShortLink


class ShortLinkForm(forms.ModelForm):
    """ форма для сокращенния ссылки """

    class Meta:
        model = ShortLink
        fields = ['full_link']

shortlink/accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render

from .forms import LoginForm, CustomUserRegisterForm


def login_view(request):
    """ функция авторизации пользователя """

    form = LoginForm()
    template_name = "login.html"
    if request.method == 'POST':
        form = LoginForm(request.POST)
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            template_name = "profile.html"
        else:
            template_name = "register_false.html"
    context = {'form': form}
    return render(request, template_name, context)


def register_view(request):
    """ функция регистрации пользователя на сайте """

    form = CustomUserRegisterForm()
    if request.method == 'POST':
        try:
            new_user = CustomUserRegisterForm(request.POST)
            new_user.save()
            return render(request, 'successful_register.html')
        except BaseException:
            return render(request, "register_false.html")

    context = {'form': form}
    return render(request, 'register_form.html', context)


def get_profile(request):
    """ функция для отображения профиля авторизованного пользователя """
    return render(request, 'profile.html')


def logout_view(request):
    """ функция выхода из аккаунта пользователя """
    logout(request)
    return render(request, 'start_page.html')

shortlink/main/views.py
import secrets
import string

from django.db import IntegrityError
from django.shortcuts import render, redirect
from accounts.models import CustomUser

from .models import ShortLink
from .forms import ShortLinkForm


def start_page(request):
    """ стартовая страница сайта """
    return render(request, 'start_page.html')


def generate_short_url(length):
    """ метод трансформации длинной ссылки в короткую """

    first_part_url = 'http://127.0.0.1:8000/'
    letters_digits = string.ascii_letters + string.digits
    last_part_url = ''.join(secrets.choice(letters_digits) for i in range(length))
    return first_part_url + last_part_url


def short_link(request):
    """ функция для получения пользователем короткой ссылки из длинной """

    form = ShortLinkForm()
    if request.user.username:
        user = CustomUser.objects.get(username=request.user.username)
        if request.method == 'POST':
            link = ShortLink(full_link=request.POST.get("full_link"), user=user, slug=generate_short_url(6))
            try:
                link.save()
            except IntegrityError:
                link = ShortLink.objects.get(full_link=request.POST.get("full_link"))
            context = {'link': link}
            return render(request, "transformation.html", context)
    context = {'form': form}
    return render(request, 'short_link.html', context)


def revers_transformation(request, slug):
    """ функция перенаправления на страницу с полным url-адресом """

    link = ShortLink.objects.get(slug='http://127.0.0.1:8000/' + slug)
    return redirect(link.full_link)


def list_links(request):
    """ функция вывода списка сокращенных ссылок авторизованного пользователя """

    if request.user.username:
        user = CustomUser.objects.get(username=request.user.username)
        links = ShortLink.objects.filter(user=user)
        context = {'links': links, 'user': user}
        return render(request, 'list_links.html', context)

shortlink/accounts/templates/login.html
{% extends "start_page.html" %}

{% block content %}
<h2> Введите логин и пароль: </h2>

<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button> Войти</button>
</form>

{% endblock %}>

shortlink/accounts/templates/profile.html
{% extends "start_page.html" %}
{% load static %}

{% block content %}
<div style="display: flex; justify-content: center; background-color: darkolivegreen">
<a href="{% url 'main:short_link' %}" style="padding:25px; text-decoration: none; color:white"> <h3>Сократить ссылку</h3> </a>
<a href="{% url 'main:list_links' %}" style="padding:25px; text-decoration: none; color:white"> <h3>Список моих ссылок </h3> </a>
<a href="{% url 'accounts:logout' %}" style="padding:25px; text-decoration: none; color:white"> <h3>Выйти </h3> </a>

</div>
{% endblock %}

shortlink/accounts/templates/register_false.html
{% extends "start_page.html" %}

{% block content %}
<h4> Введеные пароли не совпадают или не соответсвуют описаным требованиям</h4>



{% endblock %}

shortlink/accounts/templates/register_form.html
{% extends 'start_page.html' %}

{% block content %}
<h2> Для регистрации заполните форму: </h2>
    <form actoin="" method ="post">
        {% csrf_token %}
    <table> {{ form.as_table }} </table>
    <button> Зарегистрироваться </button>
    </form>
{% endblock %}

shortlink/accounts/templates/successful_register.html
{% extends 'start_page.html' %}

{% block content %}
<h4> Регистрация прошла успешно </h4>
<h4> Пройдите авторизацию </h4>
<h3> </h3>
{% endblock %}

shortlink/main/templates/list_links.html
{% extends "profile.html" %}

{% block link %}
<h3> Cписок сокращенных ссылок пользователя  {{ user }}</h3>

<table width="100%" border="5" >
    <tr>
        <th width="30%">Сокращенная ссылка</th>
        <th width="70%">Полная ссылка</th>
    </tr>
    {% for link in links %}
    <tr>
        <td width="30%"> {{ link.slug }}</td>
        <td width="70%"> {{ link.full_link }}</td>
    </tr>
    {% endfor %}
</table>


{% endblock %}

shortlink/main/templates/short_link.html
{% extends "profile.html" %}


{% block link %}
<h2> Введите полную ссылку: </h2>

<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button> Сократить</button>
</form>

{% endblock %}

shortlink/main/templates/start_page.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/start_page.css' %}">

</head>
<body>
<main>
    <div style="display: flex; justify-content: center; background-color: teal">
        <a href="{% url 'accounts:register' %}" style="padding:35px; text-decoration: none; color:white">Регистрация</a>
        {% if user.is_authenticated %}
        <a href="{% url 'accounts:profile' %}" style="padding:35px; text-decoration: none; color:white">Мой профиль</a>
        {% else %}
        <a href="{% url 'accounts:login' %}" style="padding:35px; text-decoration: none; color:white">Авторизация</a>
        {% endif %}
    </div>
    {% block content %}
    {% endblock %}
    {% block link %}
    {% endblock %}
</main>

<div style="display: flex; justify-content: center; background-color: chocolate">
    <a href="http://127.0.0.1:8000/" style="padding:15px; text-decoration: none; color:white"><h1>ShortLink</h1></a>
</div>
</body>
</html>

shortlink/main/templates/transformation.html
{% extends "profile.html" %}

{% block link %}
<h2> Сокращение ссылки </h2>


<table width="100%" border="5">
    <tr >
        <th width="200">Сокращенная ссылка</th>
        <th width="500">Полная ссылка</th>
    </tr>
    <tr>
        <td> {{ link.slug }}</td>
        <td> {{ link.full_link }}</td>
    </tr>
</table>


{% endblock %}>